# Generated by Django 6.0.7 on 2026-07-18 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.TextField(unique=True)),
                ('material_type', models.IntegerField(choices=[(1, 'Weekly Boss'), (2, 'Forgery')])),
                ('rarity', models.IntegerField(choices=[(1, 'Green'), (2, 'Blue'), (3, 'Purple'), (4, 'Gold')])),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Resonators',
            fields=[
                ('resonator_id', models.AutoField(primary_key=True, serialize=False)),
                ('character_name', models.TextField(unique=True)),
                ('is_counted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Resonators',
            },
        ),
        migrations.CreateModel(
            name='Forte_Costs',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('forte_node', models.IntegerField(choices=[(1, 'Basic Attack'), (2, 'Resonance Skill'), (3, 'Forte Circuit'), (4, 'Resonance Liberation'), (5, 'Intro Skill'), (6, 'Inherent Skill'), (7, 'Stat Bonus')])),
                ('stat_branch', models.IntegerField(blank=True, choices=[(1, 'Stat Bonus 1'), (2, 'Stat Bonus 2'), (3, 'Stat Bonus 3'), (4, 'Stat Bonus 4')], null=True)),
                ('node_cost', models.IntegerField()),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WuWa.materials')),
                ('resonators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WuWa.resonators')),
            ],
            options={
                'verbose_name_plural': 'Forte Costs',
            },
        ),
    ]
