# Generated by Django 6.0.7 on 2026-07-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WuWa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forte_costs',
            name='target_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
